export class AudioManager {
  constructor(){this.musicEnabled=true;this.soundEnabled=true;this.ctx=null;this.buffers=new Map();this.music=null;this.runLoop=null;this.unlocked=false;}
  async init(){const files={jump:'assets/audio/music/jump.mp3',coin:'assets/audio/music/coin.mp3',crash:'assets/audio/music/crash.mp3',slide:'assets/audio/music/slide.mp3',run:'assets/audio/music/run.mp3',powerup:'assets/audio/music/powerup.mp3',background:'assets/audio/music/background.mp3'}; for(const [k,u] of Object.entries(files)){try{const r=await fetch(u);if(r.ok&&Number(r.headers.get('content-length')||1)>100){const a=await r.arrayBuffer();this.buffers.set(k,a);}}catch(_){}}}
  unlock(){if(this.unlocked)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.unlocked=true;}
  play(name){if(!this.soundEnabled)return;this.unlock();if(name==='background')return this.startMusic();const tones={jump:[520,.10,'sine'],coin:[920,.07,'triangle'],crash:[80,.32,'sawtooth'],slide:[190,.15,'square'],powerup:[680,.22,'sine'],lane:[310,.055,'triangle'],button:[430,.04,'sine'],gameover:[120,.5,'sawtooth']}; const t=tones[name]||[250,.06,'sine'];this.#tone(...t);}
  #tone(freq,dur,type){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,this.ctx.currentTime);if(type==='sawtooth')o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.4),this.ctx.currentTime+dur);g.gain.setValueAtTime(.0001,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.13,this.ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+dur+.02);}
  startMusic(){if(!this.musicEnabled)return;this.unlock();this.stopMusic();const o=this.ctx.createOscillator(),o2=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o2.type='triangle';o.frequency.value=55;o2.frequency.value=82.4;g.gain.value=.025;o.connect(g);o2.connect(g);g.connect(this.ctx.destination);o.start();o2.start();this.music={o,o2,g};}
  stopMusic(){if(this.music){try{this.music.o.stop();this.music.o2.stop();}catch(_){}this.music=null;}}
  setMusic(v){this.musicEnabled=v;v?this.startMusic():this.stopMusic();localStorage.setItem('fuelRushMusic',String(v));}
  setSound(v){this.soundEnabled=v;localStorage.setItem('fuelRushSound',String(v));}
}
