
class Game {
  constructor(gameScene,audio,ui){this.gs=gameScene;this.scene=gameScene.scene;this.audio=audio;this.ui=ui;this.player=new Player(this.scene,audio);this.effects=new Effects(this.scene);this.objects=[];this.state='menu';this.speed=18;this.score=0;this.distance=0;this.coins=0;this.spawnTimer=0;this.powerups={Magnet:0,'Double Coins':0,Shield:0,'Speed Boost':0,'Jump Boost':0,Invincible:0};this.high=Number(localStorage.getItem('fuelRushHigh')||0);this.pool=[];}
  async init(progress){await this.player.init(progress);}
  start(){this.clearObjects();this.state='running';this.speed=18;this.score=0;this.distance=0;this.coins=0;this.spawnTimer=.5;for(const k in this.powerups)this.powerups[k]=0;this.player.reset();this.ui.hideScreens();this.ui.hud(true);this.audio.startMusic();}
  pause(){if(this.state!=='running')return;this.state='paused';this.ui.show('pause-menu');}
  resume(){if(this.state!=='paused')return;this.state='running';this.ui.hideScreens();}
  menu(){this.state='menu';this.clearObjects();this.ui.hud(false);this.ui.show('main-menu');this.audio.stopMusic();}
  update(dt){const running=this.state==='running';this.player.update(dt,running,this.powerups['Jump Boost']>0?1.25:1);this.effects.update(dt,this.speed);if(!running)return;dt=Math.min(dt,.04);this.speed=Math.min(44,this.speed+dt*.34);const worldSpeed=this.speed*(this.powerups['Speed Boost']>0?1.22:1);this.gs.updateRoad(dt,worldSpeed);this.gs.follow(this.player,dt,worldSpeed);this.distance+=worldSpeed*dt*.42;this.score+=dt*worldSpeed*(this.powerups['Double Coins']>0?2:1);this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawnPattern();this.spawnTimer=Math.max(.52,1.45-this.speed*.018)+Math.random()*.35;}for(const k in this.powerups)this.powerups[k]=Math.max(0,this.powerups[k]-dt);this.player.invincible=this.powerups.Invincible>0||this.powerups.Shield>0;this.updateObjects(dt,worldSpeed);this.ui.update(this.score,this.coins,this.distance,this.powerups['Double Coins']>0?2:1);this.ui.powerups(this.powerups);}
  updateObjects(dt,speed){for(let i=this.objects.length-1;i>=0;i--){const o=this.objects[i];o.mesh.position.z+=speed*dt;if(o.type==='moving')o.mesh.position.x=Math.sin(performance.now()*.002+o.phase)*2.5;if(o.spin)o.mesh.rotation.y+=dt*3.2;if(o.type==='coin'&&this.powerups.Magnet>0&&o.mesh.position.z>-15){o.mesh.position.lerp(this.player.group.position.clone().add(new THREE.Vector3(0,1,0)),dt*7);}const box=new THREE.Box3().setFromObject(o.mesh);if(box.intersectsBox(this.player.hitbox))this.collide(o,i);else if(o.mesh.position.z>15){this.scene.remove(o.mesh);this.objects.splice(i,1);}}}
  collide(o,index){if(o.type==='coin'||o.type==='token'||o.type==='star'){const add=this.powerups['Double Coins']>0?2:1;this.coins+=add;this.score+=100*add;this.audio.play('coin');this.effects.burst(o.mesh.position,0xffd24a,8);this.remove(index);return;}if(o.type==='power'){this.powerups[o.power]=o.power==='Shield'?10:8;this.audio.play('powerup');this.effects.burst(o.mesh.position,0x5bf0ff,14);this.ui.toast(o.power);this.remove(index);return;}if(this.player.invincible){if(this.powerups.Shield>0)this.powerups.Shield=0;this.effects.burst(o.mesh.position);this.remove(index);return;}this.end();}
  end(){this.state='over';this.player.hit();this.audio.play('crash');this.audio.play('gameover');this.audio.stopMusic();this.effects.burst(this.player.group.position.clone().add(new THREE.Vector3(0,1,0)),0xff4d23,32);this.high=Math.max(this.high,this.score);localStorage.setItem('fuelRushHigh',String(Math.floor(this.high)));setTimeout(()=>{this.ui.hud(false);this.ui.gameOver({score:this.score,distance:this.distance,coins:this.coins,high:this.high});},550);}
  remove(i){this.scene.remove(this.objects[i].mesh);this.objects.splice(i,1);}
  clearObjects(){for(const o of this.objects)this.scene.remove(o.mesh);this.objects=[];}
  spawnPattern(){const difficulty=Math.min(1,(this.speed-18)/25);const lanes=[-2.5,0,2.5];const safe=Math.floor(Math.random()*3);if(Math.random()<.45){for(let i=0;i<3;i++)if(i!==safe&&Math.random()<.82)this.spawnObstacle(lanes[i],-70-Math.random()*8,difficulty);}else this.spawnObstacle(lanes[Math.floor(Math.random()*3)],-70,difficulty);if(Math.random()<.78){const lane=lanes[safe];for(let z=-76;z>-92;z-=3)this.spawnCollectable(lane,z,Math.random()<.08?'power':'coin');}}
  spawnObstacle(x,z,d){const types=['barrel','barrier','block','beam','electric','hose'];const type=types[Math.floor(Math.random()*types.length)];let mesh;if(type==='barrel'){mesh=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,1.45,14),new THREE.MeshStandardMaterial({color:0x20242a,metalness:.7,roughness:.35}));mesh.position.y=.72;}else if(type==='beam'){mesh=new THREE.Group();const m=new THREE.MeshStandardMaterial({color:0x24282f,metalness:.65,roughness:.38});for(const px of [-.85,.85]){const p=new THREE.Mesh(new THREE.BoxGeometry(.18,2.8,.22),m);p.position.set(px,1.4,0);mesh.add(p);}const top=new THREE.Mesh(new THREE.BoxGeometry(1.9,.22,.28),m);top.position.y=2.72;mesh.add(top);}else if(type==='hose'){mesh=new THREE.Mesh(new THREE.TorusGeometry(.9,.13,10,28,Math.PI),new THREE.MeshStandardMaterial({color:0x08090a,roughness:.95}));mesh.rotation.x=Math.PI/2;mesh.rotation.z=Math.PI;mesh.position.y=.15;}else{const geo=type==='block'?new THREE.BoxGeometry(1.55,1.15,1):new THREE.BoxGeometry(1.7,type==='electric'?1.8:.9,.72);mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:type==='electric'?0x313841:0x24272d,metalness:.35,roughness:.55}));mesh.position.y=(type==='electric'?1.8:.9)/2;}mesh.position.x=x;mesh.position.z=z;mesh.traverse?.(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});this.scene.add(mesh);this.objects.push({mesh,type:Math.random()<d*.16?'moving':'obstacle',phase:Math.random()*6});}
  spawnCollectable(x,z,type){let mesh,power;if(type==='power'){power=['Magnet','Double Coins','Shield','Speed Boost','Jump Boost','Invincible'][Math.floor(Math.random()*6)];mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.42,0),new THREE.MeshStandardMaterial({color:0x50e3ff,emissive:0x1689aa,emissiveIntensity:2,metalness:.25,roughness:.2}));}else{mesh=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.08,18),new THREE.MeshStandardMaterial({color:0xffc12b,emissive:0x9b5b00,emissiveIntensity:.8,metalness:.7,roughness:.25}));mesh.rotation.x=Math.PI/2;}mesh.position.set(x,1.15,z);mesh.castShadow=true;this.scene.add(mesh);this.objects.push({mesh,type:type==='power'?'power':'coin',power,spin:true});}
}
