class GameScene {
  constructor(canvas){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x0c1118);this.scene.fog=new THREE.Fog(0x0c1118,35,135);this.camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,240);this.camera.position.set(0,5.1,12.5);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputEncoding=THREE.sRGBEncoding;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.world=new THREE.Group();this.scene.add(this.world);this.roadSegments=[];this.decor=[];this.#lights();this.#world();addEventListener('resize',()=>this.resize());}
  #lights(){this.scene.add(new THREE.HemisphereLight(0xbfd7ff,0x202018,1.35));const sun=new THREE.DirectionalLight(0xfff0d4,3.2);sun.position.set(-12,20,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=22;sun.shadow.camera.bottom=-12;this.scene.add(sun);}
  #world(){const asphalt=new THREE.MeshStandardMaterial({color:0x171b21,roughness:.9,metalness:.02});const line=new THREE.MeshStandardMaterial({color:0xe3a82c,emissive:0x5c3400,emissiveIntensity:.18,roughness:.55});for(let i=0;i<8;i++){const seg=new THREE.Group();const road=new THREE.Mesh(new THREE.BoxGeometry(10,.18,24),asphalt);road.position.y=-.12;road.receiveShadow=true;seg.add(road);for(const x of [-1.25,1.25]){for(let z=-10;z<=10;z+=4){const mark=new THREE.Mesh(new THREE.BoxGeometry(.08,.025,2.2),line);mark.position.set(x,.01,z);seg.add(mark);}}for(const x of [-5.1,5.1]){const curb=new THREE.Mesh(new THREE.BoxGeometry(.35,.28,24),new THREE.MeshStandardMaterial({color:0x2c3139,roughness:.75}));curb.position.set(x,.02,0);curb.receiveShadow=true;seg.add(curb);}seg.position.z=-i*24;this.world.add(seg);this.roadSegments.push(seg);this.#decorate(seg,i);}}
  #decorate(seg,idx){const dark=new THREE.MeshStandardMaterial({color:0x242931,roughness:.5,metalness:.55}),yellow=new THREE.MeshStandardMaterial({color:0xe89b13,roughness:.45,metalness:.2});for(const side of [-1,1]){const x=side*7.2;const frame=new THREE.Group();const pole=new THREE.Mesh(new THREE.CylinderGeometry(.12,.14,5.2,8),dark);pole.position.y=2.5;pole.castShadow=true;frame.add(pole);const sign=new THREE.Mesh(new THREE.BoxGeometry(2.2,1.05,.16),yellow);sign.position.set(0,4.6,0);sign.castShadow=true;frame.add(sign);const cable=new THREE.Mesh(new THREE.TorusGeometry(.72,.045,7,20,Math.PI*1.5),new THREE.MeshStandardMaterial({color:0x08090a,roughness:.9}));cable.position.set(.5,2.2,0);cable.rotation.y=Math.PI/2;frame.add(cable);frame.position.set(x,0,(idx%2?5:-5));seg.add(frame);this.decor.push(frame);}}
  updateRoad(dt,speed){for(const seg of this.roadSegments){seg.position.z+=speed*dt;if(seg.position.z>24)seg.position.z-=this.roadSegments.length*24;}}
  follow(player,dt,speed){const targetX=player.group.position.x*.38;this.camera.position.x=THREE.MathUtils.damp(this.camera.position.x,targetX,4.5,dt);this.camera.position.y=THREE.MathUtils.damp(this.camera.position.y,5.0+player.group.position.y*.25,5,dt);this.camera.position.z=12.6;this.camera.lookAt(player.group.position.x*.18,1.3+player.group.position.y*.25,-4-speed*.05);}
  resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));}
  render(){this.renderer.render(this.scene,this.camera);}
}
